# -*- coding: utf-8 -*-
"""energy_dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c3QGUzK7bt1fgrCdVl6-HOPCEUS885II
"""

# energy_dashboard.py

# Install necessary libraries if running standalone (e.g., in a new environment)
# pip install streamlit pandas numpy matplotlib seaborn plotly requests

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px # For interactive plots
import requests # To call your FastAPI endpoint (if running locally or deployed)
import json # For handling JSON data from API
import os # For checking file existence
from datetime import datetime, date # Import date for prediction_date in API request

# --- Configuration ---
st.set_page_config(layout="wide", page_title="Domestic Energy Optimization Dashboard")

# --- Model API Endpoint (Update if your API is deployed) ---
# If your FastAPI is running locally, use http://127.0.0.1:8000
# If deployed, replace with your deployed API URL
API_URL = "http://127.0.0.1:8000" # Placeholder: Update with your actual API URL if deployed

# --- Helper Function to Call API ---
def get_prediction_from_api(endpoint: str, input_data: dict):
    """Sends input data to the specified API endpoint and returns the JSON response."""
    try:
        response = requests.post(f"{API_URL}/{endpoint}", json=input_data)
        response.raise_for_status() # Raise an HTTPError for bad responses (4xx or 5xx)
        return response.json()
    except requests.exceptions.ConnectionError:
        st.error(f"API connection error: Could not connect to {API_URL}. Please ensure the API is running.")
        return None
    except requests.exceptions.HTTPError as e:
        st.error(f"API HTTP error: {e}. Detail: {response.json().get('detail', 'No detail provided')}")
        return None
    except Exception as e:
        st.error(f"An unexpected error occurred when calling the API: {e}")
        return None

# --- Dummy Data Loading (for demonstration if API is not available) ---
@st.cache_data # Cache data loading to avoid re-running on every interaction
def load_sample_data(path="/Users/barki/Downloads/Dashboard/optimisation_dataset.csv", sample_frac=0.01): # Changed default path
    try:
        # --- DEBUGGING LINES START ---
        directory = os.path.dirname(path)
        # st.write(f"Attempting to load data from: `{path}`") # Commented out after debugging
        # if os.path.exists(directory):
        #     st.write(f"Contents of `{directory}`:")
        #     st.code(os.listdir(directory)) # Use st.code for better display of list
        # else:
        #     st.error(f"Directory `{directory}` does not exist. Please ensure your `optimisation_dataset.csv` is in the correct location or update the path.")
        # --- DEBUGGING LINES END ---

        df = pd.read_csv(path)
        df['date'] = pd.to_datetime(df['date'])
        # Sort by date and lclid for consistent time series operations
        df = df.sort_values(by=['lclid', 'date'])
        # Take a smaller sample for dashboard performance
        return df.sample(frac=sample_frac, random_state=42).sort_values(by=['date', 'lclid'])
    except FileNotFoundError:
        st.error(f"Dataset not found at `{path}`. Please ensure 'optimisation_dataset.csv' is in the specified location (or update the path).")
        return pd.DataFrame() # Return empty DataFrame on error
    except Exception as e:
        st.error(f"Error loading sample data: {e}")
        return pd.DataFrame()

# IMPORTANT: Before running this locally, you must manually download
# 'optimisation_dataset.csv' from your Google Drive and place it in the
# specified path: /Users/barki/Downloads/Dashboard/optimisation_dataset.csv
sample_df = load_sample_data()

# --- Dashboard Layout ---
st.title("🏡 Domestic Energy Optimization Dashboard")
st.markdown("""
Welcome to the Energy Optimization Dashboard! This tool helps you understand and predict
your household's energy consumption, cost, and carbon footprint.
""")

# --- Sidebar for Navigation/Inputs ---
st.sidebar.header("Dashboard Controls")
dashboard_mode = st.sidebar.radio(
    "Choose Mode:",
    ("Overview & Trends", "Individual Prediction", "Optimization Recommendations", "Residuals Analysis") # Added new mode
)

# --- Main Content Area ---
if dashboard_mode == "Overview & Trends":
    st.header("Overall Energy Consumption Trends")
    if not sample_df.empty:
        # Aggregate data for overall trends
        daily_summary = sample_df.groupby('date').agg(
            avg_kwh=('kwh_total', 'mean'),
            avg_cost=('predicted_cost', 'mean'),
            avg_carbon=('predicted_carbon', 'mean'),
            avg_carbon_adj_price=('carbon_adj_price', 'mean'),
            avg_max_temp_c=('max_temp_c', 'mean')
        ).reset_index()

        st.subheader("Daily Average kWh Consumption Over Time")
        fig_kwh = px.line(daily_summary, x='date', y='avg_kwh', title='Average Daily kWh Consumption')
        st.plotly_chart(fig_kwh, use_container_width=True)

        st.subheader("Daily Average Cost and Carbon Over Time")
        fig_cost_carbon = px.line(daily_summary, x='date', y=['avg_cost', 'avg_carbon'],
                                  title='Average Daily Cost (£) and Carbon (kgCO₂)')
        st.plotly_chart(fig_cost_carbon, use_container_width=True)

        st.subheader("Average Carbon-Adjusted Price Over Time")
        fig_adj_price = px.line(daily_summary, x='date', y='avg_carbon_adj_price',
                                title='Average Daily Carbon-Adjusted Price (p/kWh)')
        st.plotly_chart(fig_adj_price, use_container_width=True)

        st.subheader("Correlation Matrix of Key Features")
        # Select a subset of features for correlation
        corr_features = ['kwh_total', 'predicted_cost', 'predicted_carbon', 'min_temp_c',
                         'max_temp_c', 'rain_mm', 'humidity_%', 'cloud_cover_%',
                         'wind_speed_km/h', 'TOTAL_FLOOR_AREA', 'CURRENT_ENERGY_RATING']
        # Ensure all features exist in the DataFrame before selecting
        existing_corr_features = [f for f in corr_features if f in sample_df.columns]
        if existing_corr_features:
            corr_matrix = sample_df[existing_corr_features].corr()
            fig_corr, ax_corr = plt.subplots(figsize=(10, 8))
            sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f", ax=ax_corr)
            st.pyplot(fig_corr)
        else:
            st.warning("Not enough features available for correlation matrix.")

    else:
        st.warning("No data available to display trends. Please check dataset path.")

elif dashboard_mode == "Individual Prediction":
    st.header("Predict Energy Consumption for a Specific Scenario")
    st.info("This section allows you to input specific values and get a real-time prediction from the deployed API.")

    # Input fields for prediction
    # These inputs must match the 'EnergyPredictRequest' Pydantic model in your API
    st.subheader("Input Features")

    # Group inputs for better UI
    col1, col2, col3 = st.columns(3)

    with col1:
        st.markdown("#### Weather & Environment")
        min_temp_c = st.number_input("Min Temp (°C)", value=5.0, format="%.2f", key="pred_min_temp")
        max_temp_c = st.number_input("Max Temp (°C)", value=10.0, format="%.2f", key="pred_max_temp")
        rain_mm = st.number_input("Rain (mm)", value=1.0, format="%.2f", key="pred_rain")
        humidity_percent = st.slider("Humidity (%)", 0.0, 100.0, value=70.0, format="%.1f", key="pred_humidity")
        cloud_cover_percent = st.slider("Cloud Cover (%)", 0.0, 100.0, value=50.0, format="%.1f", key="pred_cloud")
        wind_speed_km_h = st.number_input("Wind Speed (km/h)", value=15.0, format="%.2f", key="pred_wind_speed")
        wind_direction_numerical = st.number_input("Wind Direction (Numerical)", value=180.0, format="%.2f", key="pred_wind_dir")

    with col2:
        st.markdown("#### Property Details")
        total_floor_area = st.number_input("Total Floor Area", value=80.0, format="%.2f", key="pred_floor_area")
        current_energy_rating = st.number_input("Current Energy Rating", value=70.0, format="%.2f", key="pred_energy_rating")
        built_form = st.selectbox("Built Form", ["Mid-Terrace", "Detached", "Semi-Detached", "End-Terrace", "Flat"], key="pred_built_form")
        property_type = st.selectbox("Property Type", ["House", "Flat", "Bungalow", "Maisonette"], key="pred_prop_type")
        construction_age_band = st.selectbox("Construction Age Band", [
            "England and Wales: 1900-1929", "England and Wales: 1930-1949",
            "England and Wales: 1950-1966", "England and Wales: 1967-1975",
            "England and Wales: 1976-1983", "England and Wales: 1984-1990",
            "England and Wales: 1991-1995", "England and Wales: 1996-2002",
            "England and Wales: 2003-2006", "England and Wales: 2007 onwards",
            "Scotland: 1900-1929", "Scotland: 1930-1949",
            "NO DATA!"
        ], key="pred_age_band")

    with col3:
        st.markdown("#### Temporal & Lag Features")
        prediction_date = st.date_input("Prediction Date", datetime.now().date(), key="pred_date")
        day_of_week = prediction_date.weekday()
        month = prediction_date.month
        season = (month % 12 + 3) // 3
        day_of_year_sin = np.sin(2 * np.pi * prediction_date.timetuple().tm_yday/365)
        day_of_year_cos = np.cos(2 * np.pi * prediction_date.timetuple().tm_yday/365)
        hour_of_day = st.slider("Hour of Day (0-23)", 0, 23, value=12, key="pred_hour")

        temp_humidity = max_temp_c * humidity_percent
        temp_wind = max_temp_c * wind_speed_km_h
        weather_severity = (max_temp_c * 0.3 + rain_mm * 0.2 + wind_speed_km_h * 0.5)
        size_rating = total_floor_area * current_energy_rating
        age_size = 5000.0 # Placeholder, for demo purposes

        st.markdown("##### Lag & Rolling Features (Approximate for Demo)")
        lag_1 = st.number_input("Lag 1 (kWh)", value=10.0, format="%.2f", key="pred_lag1")
        lag_2 = st.number_input("Lag 2 (kWh)", value=9.5, format="%.2f", key="pred_lag2")
        lag_3 = st.number_input("Lag 3 (kWh)", value=10.5, format="%.2f", key="pred_lag3")
        lag_7 = st.number_input("Lag 7 (kWh)", value=11.0, format="%.2f", key="pred_lag7")
        rolling_7day_mean = st.number_input("Rolling 7-day Mean (kWh)", value=10.0, format="%.2f", key="pred_rollmean")
        rolling_7day_std = st.number_input("Rolling 7-day Std (kWh)", value=1.5, format="%.2f", key="pred_rollstd")

    predict_payload = {
        "min_temp_c": min_temp_c, "max_temp_c": max_temp_c, "rain_mm": rain_mm,
        "humidity_%": humidity_percent, "cloud_cover_%": cloud_cover_percent,
        "wind_speed_km/h": wind_speed_km_h, "wind_direction_numerical": wind_direction_numerical,
        "TOTAL_FLOOR_AREA": total_floor_area, "CURRENT_ENERGY_RATING": current_energy_rating,
        "BUILT_FORM": built_form, "PROPERTY_TYPE": property_type, "CONSTRUCTION_AGE_BAND": construction_age_band,
        "day_of_week": day_of_week, "month": month, "season": season,
        "day_of_year_sin": float(day_of_year_sin), "day_of_year_cos": float(day_of_year_cos),
        "hour_of_day": hour_of_day, "temp_humidity": temp_humidity, "temp_wind": temp_wind,
        "weather_severity": weather_severity, "size_rating": size_rating, "age_size": age_size,
        "lag_1": lag_1, "lag_2": lag_2, "lag_3": lag_3, "lag_7": lag_7,
        "rolling_7day_mean": rolling_7day_mean, "rolling_7day_std": rolling_7day_std
    }

    if st.button("Get Prediction", key="get_prediction_btn"):
        with st.spinner("Getting prediction from API..."):
            prediction_response = get_prediction_from_api("predict", predict_payload)
            if prediction_response is not None:
                predicted_kwh = prediction_response.get("predicted_kwh")
                st.success(f"Predicted Energy Consumption: **{predicted_kwh:.2f} kWh**")

elif dashboard_mode == "Optimization Recommendations": # New Mode
    st.header("Appliance Optimization Recommendations 💡")
    st.info("""
        Find the optimal time to run your appliance to minimize a weighted combination of
        energy cost and carbon footprint based on predicted baseline consumption and
        mock real-time energy prices/carbon intensity.
        **Note:** Lag and rolling features are approximate for this demo.
    """)

    # --- Input Fields for Optimization ---
    col_opt1, col_opt2, col_opt3 = st.columns(3)

    with col_opt1:
        st.markdown("#### Appliance Details")
        appliance_name = st.selectbox("Appliance Name", ["Washing Machine", "Dishwasher", "EV Charger", "Tumble Dryer", "Other"], key="opt_app_name")
        appliance_kwh_per_cycle = st.number_input("Energy per Cycle (kWh)", value=2.0, format="%.2f", key="opt_app_kwh")
        optimization_date = st.date_input("Optimization Date", datetime.now().date(), key="opt_date")

    with col_opt2:
        st.markdown("#### Flexible Time Window")
        flexible_start_hour = st.slider("Flexible Start Hour (0-23)", 0, 23, value=19, key="opt_start_hour")
        flexible_end_hour = st.slider("Flexible End Hour (0-23)", 0, 23, value=23, key="opt_end_hour")
        if flexible_start_hour > flexible_end_hour:
            st.warning("Start hour cannot be after end hour. Adjusting end hour.")
            flexible_end_hour = flexible_start_hour # Auto-correct for user

    with col_opt3:
        st.markdown("#### Optimization Priority")
        cost_weight = st.slider("Prioritize Cost (%)", 0.0, 100.0, value=50.0, format="%.0f", key="opt_cost_weight") / 100
        carbon_weight = st.slider("Prioritize Carbon (%)", 0.0, 100.0, value=50.0, format="%.0f", key="opt_carbon_weight") / 100
        if not (cost_weight + carbon_weight == 1.0):
            st.info("Cost and Carbon weights should sum to 100%. Adjusting for visualization.")
            # Adjust one if user moves the other, assuming preference for cost slider
            if cost_weight + carbon_weight != 0:
                carbon_weight = 1.0 - cost_weight
                st.slider("Prioritize Carbon (%) (Adjusted)", 0.0, 100.0, value=carbon_weight * 100, format="%.0f", disabled=True)


    st.markdown("#### Baseline Features (from Individual Prediction for consistency)")
    st.info("These features are used to predict the baseline energy consumption for each hour in the window.")
    col_base1, col_base2, col_base3 = st.columns(3)
    with col_base1:
        min_temp_c = st.number_input("Min Temp (°C)", value=5.0, format="%.2f", key="opt_min_temp")
        max_temp_c = st.number_input("Max Temp (°C)", value=10.0, format="%.2f", key="opt_max_temp")
        rain_mm = st.number_input("Rain (mm)", value=1.0, format="%.2f", key="opt_rain")
        humidity_percent = st.slider("Humidity (%)", 0.0, 100.0, value=70.0, format="%.1f", key="opt_humidity")
        cloud_cover_percent = st.slider("Cloud Cover (%)", 0.0, 100.0, value=50.0, format="%.1f", key="opt_cloud")
        wind_speed_km_h = st.number_input("Wind Speed (km/h)", value=15.0, format="%.2f", key="opt_wind_speed")
        wind_direction_numerical = st.number_input("Wind Direction (Numerical)", value=180.0, format="%.2f", key="opt_wind_dir")
    with col_base2:
        total_floor_area = st.number_input("Total Floor Area", value=80.0, format="%.2f", key="opt_floor_area")
        current_energy_rating = st.number_input("Current Energy Rating", value=70.0, format="%.2f", key="opt_energy_rating")
        built_form = st.selectbox("Built Form", ["Mid-Terrace", "Detached", "Semi-Detached", "End-Terrace", "Flat"], key="opt_built_form")
        property_type = st.selectbox("Property Type", ["House", "Flat", "Bungalow", "Maisonette"], key="opt_prop_type")
        construction_age_band = st.selectbox("Construction Age Band", [
            "England and Wales: 1900-1929", "England and Wales: 1930-1949",
            "England and Wales: 1950-1966", "England and Wales: 1967-1975",
            "England and Wales: 1976-1983", "England and Wales: 1984-1990",
            "England and Wales: 1991-1995", "England and Wales: 1996-2002",
            "England and Wales: 2003-2006", "England and Wales: 2007 onwards",
            "Scotland: 1900-1929", "Scotland: 1930-1949",
            "NO DATA!"
        ], key="opt_age_band")
    with col_base3:
        # Lag and Rolling features - still approximate for demo
        lag_1 = st.number_input("Lag 1 (kWh)", value=10.0, format="%.2f", key="opt_lag1")
        lag_2 = st.number_input("Lag 2 (kWh)", value=9.5, format="%.2f", key="opt_lag2")
        lag_3 = st.number_input("Lag 3 (kWh)", value=10.5, format="%.2f", key="opt_lag3")
        lag_7 = st.number_input("Lag 7 (kWh)", value=11.0, format="%.2f", key="opt_lag7")
        rolling_7day_mean = st.number_input("Rolling 7-day Mean (kWh)", value=10.0, format="%.2f", key="opt_rollmean")
        rolling_7day_std = st.number_input("Rolling 7-day Std (kWh)", value=1.5, format="%.2f", key="opt_rollstd")


    optimization_payload = {
        "min_temp_c": min_temp_c, "max_temp_c": max_temp_c, "rain_mm": rain_mm,
        "humidity_%": humidity_percent, "cloud_cover_%": cloud_cover_percent,
        "wind_speed_km/h": wind_speed_km_h, "wind_direction_numerical": wind_direction_numerical,
        "TOTAL_FLOOR_AREA": total_floor_area, "CURRENT_ENERGY_RATING": current_energy_rating,
        "BUILT_FORM": built_form, "PROPERTY_TYPE": property_type, "CONSTRUCTION_AGE_BAND": construction_age_band,
        "lag_1": lag_1, "lag_2": lag_2, "lag_3": lag_3, "lag_7": lag_7,
        "rolling_7day_mean": rolling_7day_mean, "rolling_7day_std": rolling_7day_std,
        "appliance_name": appliance_name,
        "appliance_kwh_per_cycle": appliance_kwh_per_cycle,
        "optimization_date": optimization_date.isoformat(), # Send date as ISO format string
        "flexible_start_hour": flexible_start_hour,
        "flexible_end_hour": flexible_end_hour,
        "cost_weight": cost_weight,
        "carbon_weight": carbon_weight
    }

    if st.button("Find Optimal Time", key="find_optimal_time_btn"):
        with st.spinner("Calculating optimal time..."):
            optimization_response = get_prediction_from_api("optimize_appliance", optimization_payload)
            if optimization_response:
                st.subheader("Optimal Time Recommendation")
                optimal_hour = optimization_response.get("optimal_hour_to_run")
                optimal_details = optimization_response.get("optimal_hour_details", {})

                st.success(f"For your **{optimization_response.get('appliance_name')}**, the optimal time to run on "
                           f"**{optimization_response.get('optimization_date')}** is **{optimal_hour}:00**.")
                st.write(f"This is projected to result in:")
                st.metric("Total Cost", f"£{optimal_details.get('total_cost_pounds', 0):.2f}")
                st.metric("Total Carbon Footprint", f"{optimal_details.get('total_carbon_kgCO2', 0):.2f} kgCO2")
                st.metric("Total Predicted kWh (with appliance)", f"{optimal_details.get('total_kwh', 0):.2f} kWh")

                st.subheader("Hourly Breakdown")
                hours_df = pd.DataFrame(optimization_response.get("all_hours_details"))
                hours_df['hour_label'] = hours_df['hour'].astype(str) + ':00'

                fig_obj = px.bar(hours_df, x='hour_label', y='objective_value',
                                 title='Objective Value (Cost + Carbon) per Hour',
                                 labels={'objective_value': 'Weighted Cost/Carbon', 'hour_label': 'Hour'},
                                 color='objective_value',
                                 color_continuous_scale=px.colors.sequential.Viridis_r)
                fig_obj.add_vline(x=optimal_hour, line_dash="dot", line_color="red", # Changed best_hour to optimal_hour
                                  annotation_text=f"Optimal Hour: {optimal_hour}:00", annotation_position="top")
                st.plotly_chart(fig_obj, use_container_width=True)

                fig_cost_carbon_breakdown = px.bar(hours_df, x='hour_label', y=['total_cost_pounds', 'total_carbon_kgCO2'],
                                                   title='Cost and Carbon Footprint Breakdown per Hour (with appliance)',
                                                   labels={'value': 'Value', 'variable': 'Metric', 'hour_label': 'Hour'},
                                                   barmode='group')
                st.plotly_chart(fig_cost_carbon_breakdown, use_container_width=True)

elif dashboard_mode == "Residuals Analysis":
    st.header("Model Residuals Analysis")
    st.info("This section visualizes the errors (residuals) of the model on the test data.")

    if not sample_df.empty and 'kwh_total' in sample_df.columns and 'predicted_kwh' in sample_df.columns:
        residuals = sample_df['kwh_total'] - sample_df['predicted_kwh']

        st.subheader("Residuals Distribution")
        fig_hist, ax_hist = plt.subplots(figsize=(10, 6))
        sns.histplot(residuals, kde=True, ax=ax_hist)
        ax_hist.set_title("Residuals Distribution")
        ax_hist.set_xlabel("Prediction Error (kWh)")
        st.pyplot(fig_hist)

        st.subheader("Residuals vs. Predicted Values")
        fig_scatter, ax_scatter = plt.subplots(figsize=(10, 6))
        sns.scatterplot(x=sample_df['predicted_kwh'], y=residuals, alpha=0.3, ax=ax_scatter)
        ax_scatter.axhline(0, color='red', linestyle='--')
        ax_scatter.set_title("Residuals vs Predicted Values")
        ax_scatter.set_xlabel("Predicted Consumption (kWh)")
        ax_scatter.set_ylabel("Residuals")
        st.pyplot(fig_scatter)

        st.subheader("Residuals by Key Features")
        features_for_residuals = ['TOTAL_FLOOR_AREA', 'max_temp_c', 'day_of_year_sin']
        for feature in features_for_residuals:
            if feature in sample_df.columns:
                fig_feat, ax_feat = plt.subplots(figsize=(10, 6))
                sns.scatterplot(x=sample_df[feature], y=residuals, alpha=0.3, ax=ax_feat)
                ax_feat.axhline(0, color='red', linestyle='--')
                ax_feat.set_title(f"Residuals by {feature}")
                ax_feat.set_xlabel(feature)
                ax_feat.set_ylabel("Residuals")
                st.pyplot(fig_feat)
            else:
                st.warning(f"Feature '{feature}' not found in sample data for residuals plot.")
    else:
        st.warning("Not enough data or required columns (`kwh_total`, `predicted_kwh`) in sample data for residuals analysis.")