# -*- coding: utf-8 -*-
"""Project source code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gpoAGWX3EmH4l_eS6hdRx5aCPxPDtopY
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install pandas pyarrow --quiet
import pandas as pd
import os
import gc
from datetime import datetime
from google.colab import drive

# Clean up space
print(f"[{datetime.now()}] Cleaning up temporary files...")
!rm -rf /content/sample_data
!rm -rf /content/tmp/*
!rm -f /content/*.png /content/*.jpg /content/*.jpeg

# Mount Google Drive
print(f"[{datetime.now()}] Mounting Google Drive...")
drive.mount('/content/drive', force_remount=True)

# Define file paths
main_data_path = "/content/drive/MyDrive/final_ml_dataset_cleaned.csv"
pricing_path = "/content/drive/MyDrive/simulated_tou_pricing_2011-2014.csv"
carbon_path = "/content/drive/MyDrive/carbon_intensity_2011-2014.csv"
output_path = "/content/drive/MyDrive/optimisation_dataset.csv"

# Verify files exist
print(f"[{datetime.now()}] Verifying input files...")
for path in [main_data_path, pricing_path, carbon_path]:
    if not os.path.exists(path):
        raise FileNotFoundError(f"Required file not found: {path}")
    size_mb = os.path.getsize(path) / (1024 * 1024)
    print(f"Found file: {path} ({size_mb:.2f} MB)")

# Load and preprocess supplementary data
print(f"[{datetime.now()}] Loading and preprocessing supplementary data...")

# Load pricing data and ensure no duplicate dates
pricing_df = pd.read_csv(pricing_path, parse_dates=['date'])
print(f"Pricing data rows: {len(pricing_df)}")
if pricing_df['date'].duplicated().any():
    print("Duplicate dates found in pricing data. Taking first occurrence.")
    pricing_df = pricing_df.drop_duplicates(subset=['date'], keep='first')

# Load carbon data and aggregate to daily averages
print("Processing carbon data...")
carbon_df = pd.read_csv(carbon_path, parse_dates=['timestamp'])
print(f"Carbon data rows: {len(carbon_df)}")

# Extract date from timestamp and aggregate
carbon_df['date'] = carbon_df['timestamp'].dt.date
carbon_daily = carbon_df.groupby('date')['intensity'].mean().reset_index()
carbon_daily['date'] = pd.to_datetime(carbon_daily['date'])
carbon_daily = carbon_daily.rename(columns={'intensity': 'carbon_intensity'})

print(f"Daily carbon data rows: {len(carbon_daily)}")

# Prepare output file
print(f"[{datetime.now()}] Preparing output file...")
header = "lclid,tariff,date,min_temp_c,max_temp_c,rain_mm,humidity_%,cloud_cover_%,wind_speed_km/h,wind_direction_numerical,POSTCODE,CURRENT_ENERGY_RATING,TOTAL_FLOOR_AREA,BUILT_FORM,PROPERTY_TYPE,CONSTRUCTION_AGE_BAND,kwh_total,price_per_kwh,carbon_intensity,predicted_cost,predicted_carbon,carbon_adj_price"
with open(output_path, 'w') as f:
    f.write(header + "\n")

# Process main data in chunks
chunk_size = 50000  # 50k rows per chunk
processed_rows = 0
chunk_counter = 0

print(f"[{datetime.now()}] Starting chunked processing...")
for chunk in pd.read_csv(main_data_path, chunksize=chunk_size, parse_dates=['date']):
    chunk_counter += 1
    start_time = datetime.now()
    original_rows = len(chunk)

    print(f"\nProcessing chunk {chunk_counter} | Rows: {original_rows}")
    print(f"First date: {chunk['date'].iloc[0]} | Last date: {chunk['date'].iloc[-1]}")

    # Merge with pricing data - FIXED COLUMN NAME
    chunk = pd.merge(chunk, pricing_df[['date', 'price_per_kwh']],
                     on='date', how='left')

    # Merge with daily carbon data - FIXED COLUMN NAME
    chunk = pd.merge(chunk, carbon_daily[['date', 'carbon_intensity']],  # CHANGED FROM 'intensity' TO 'carbon_intensity'
                     on='date', how='left')

    # Check if merge caused row explosion
    if len(chunk) != original_rows:
        print(f"WARNING: Row count changed from {original_rows} to {len(chunk)} after merge!")

    # Calculate metrics
    chunk['predicted_cost'] = chunk['kwh_total'] * chunk['price_per_kwh'] / 100
    chunk['predicted_carbon'] = chunk['kwh_total'] * chunk['carbon_intensity'] / 1000
    chunk['carbon_adj_price'] = chunk['price_per_kwh'] * (1 + 0.005 * chunk['carbon_intensity'])

    # Append to output file
    chunk.to_csv(output_path, mode='a', header=False, index=False)

    # Memory cleanup
    processed_rows += len(chunk)
    del chunk
    gc.collect()

    # Progress reporting
    elapsed = (datetime.now() - start_time).total_seconds()
    rows_per_sec = original_rows / elapsed if elapsed > 0 else 0
    print(f"[{datetime.now()}] Processed chunk {chunk_counter}: {processed_rows} rows | "
          f"Time: {elapsed:.1f}s | Speed: {rows_per_sec:.1f} rows/sec")

print(f"[{datetime.now()}] Processing completed! Total rows processed: {processed_rows}")
print("Enhanced dataset saved successfully to Google Drive")

import pandas as pd
from google.colab import drive

# Mount Google Drive (if not already mounted)
try:
    drive.mount('/content/drive')
    print("Google Drive mounted successfully.")
except Exception as e:
    print(f"Could not mount Google Drive. Error: {e}")
    # If drive cannot be mounted, the script will likely fail on file loading.

# Define the path to your optimisation dataset CSV
OUTPUT_DATASET_PATH = "/content/drive/MyDrive/optimisation_dataset.csv"

# Read the entire CSV to allow for full inspection.
# For very large files, consider reading in chunks if memory becomes an issue,
# but for displaying head/tail/info, it's usually loaded fully.
try:
    optimisation_df = pd.read_csv(OUTPUT_DATASET_PATH)
    print(f"Loaded {len(optimisation_df)} rows from {OUTPUT_DATASET_PATH}.")

    # Display general information about the DataFrame (includes column names and non-null counts)
    print(f"\n--- Info for {OUTPUT_DATASET_PATH} ---")
    optimisation_df.info()

    # Display all column names
    print(f"\n--- All columns in {OUTPUT_DATASET_PATH} ---")
    print(optimisation_df.columns.tolist())

    # Display the first 10 rows of the DataFrame
    print(f"\n--- First 10 rows of {OUTPUT_DATASET_PATH} ---")
    print(optimisation_df.head(3))

    # Display the last 10 rows of the DataFrame
    print(f"\n--- Last 10 rows of {OUTPUT_DATASET_PATH} ---")
    print(optimisation_df.tail(3))

    # --- New: Count of rows by year ---
    print(f"\n--- Row Count by Year in {OUTPUT_DATASET_PATH} ---")
    # Ensure 'date' column is datetime type
    optimisation_df['date'] = pd.to_datetime(optimisation_df['date'])
    # Extract year and count rows per year
    rows_by_year = optimisation_df['date'].dt.year.value_counts().sort_index()
    print(rows_by_year)

    # Check for date range completeness
    print("Date range:", df['date'].min(), "to", df['date'].max())

    # Verify daily coverage consistency
    daily_counts = df.groupby(df['date'].dt.year)['date'].value_counts().reset_index(name='count')
    print("Average daily entries per year:")
    print(daily_counts.groupby('level_0')['count'].mean())

except FileNotFoundError:
    print(f"Error: The file '{OUTPUT_DATASET_PATH}' was not found. Please check the path.")
except Exception as e:
    print(f"An error occurred while reading or inspecting the data: {e}")

from google.colab import drive

try:
    drive.mount('/content/drive')
    print("Google Drive mounted successfully.")
except Exception as e:
    print(f"Could not mount Google Drive. Error: {e}")

import pandas as pd
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

# Load data
df = pd.read_csv("/content/drive/MyDrive/optimisation_dataset.csv")
df['date'] = pd.to_datetime(df['date'])

# Temporal features
df['day_of_year_sin'] = np.sin(2 * np.pi * df['date'].dt.dayofyear/365)
df['day_of_year_cos'] = np.cos(2 * np.pi * df['date'].dt.dayofyear/365)
df['hour_of_day'] = df['date'].dt.hour  # If hourly data exists

# Weather interactions
df['temp_humidity'] = df['max_temp_c'] * df['humidity_%']
df['temp_wind'] = df['max_temp_c'] * df['wind_speed_km/h']
df['weather_severity'] = (df['max_temp_c'] * 0.3 +
                         df['rain_mm'] * 0.2 +
                         df['wind_speed_km/h'] * 0.5)

# Property interactions
df['size_rating'] = df['TOTAL_FLOOR_AREA'] * df['CURRENT_ENERGY_RATING']
df['age_size'] = df['CONSTRUCTION_AGE_BAND'].astype('category').cat.codes * df['TOTAL_FLOOR_AREA']

# Lag features (if time series)
for lag in [1, 2, 3, 7]:
    df[f'lag_{lag}'] = df.groupby('lclid')['kwh_total'].shift(lag)

# Rolling statistics
df['rolling_7day_mean'] = df.groupby('lclid')['kwh_total'].transform(
    lambda x: x.rolling(7).mean())
df['rolling_7day_std'] = df.groupby('lclid')['kwh_total'].transform(
    lambda x: x.rolling(7).std())

# Handle missing values from lag features
df.fillna(method='bfill', inplace=True)

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.ensemble import StackingRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from sklearn.linear_model import ElasticNet
from sklearn.model_selection import TimeSeriesSplit

# Define features
features = [
    # Original features
    'min_temp_c', 'max_temp_c', 'rain_mm', 'humidity_%', 'cloud_cover_%',
    'wind_speed_km/h', 'wind_direction_numerical', 'TOTAL_FLOOR_AREA',
    'CURRENT_ENERGY_RATING', 'BUILT_FORM', 'PROPERTY_TYPE', 'CONSTRUCTION_AGE_BAND',

    # Engineered features
    'day_of_year_sin', 'day_of_year_cos', 'temp_humidity', 'temp_wind',
    'weather_severity', 'size_rating', 'age_size', 'lag_1', 'lag_2', 'lag_7',
    'rolling_7day_mean', 'rolling_7day_std'
]

# Preprocessing
numeric_features = [f for f in features if f not in ['BUILT_FORM', 'PROPERTY_TYPE', 'CONSTRUCTION_AGE_BAND']]
categorical_features = ['BUILT_FORM', 'PROPERTY_TYPE', 'CONSTRUCTION_AGE_BAND']

preprocessor = ColumnTransformer([
    ('num', StandardScaler(), numeric_features),
    ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
])

# Base models
xgb = XGBRegressor(
    n_estimators=500,
    max_depth=8,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    gamma=0.1,
    random_state=42
)

lgbm = LGBMRegressor(
    n_estimators=500,
    max_depth=7,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

# Meta model
meta_model = ElasticNet(alpha=0.01, l1_ratio=0.5)

# Stacked ensemble
stacked_model = StackingRegressor(
    estimators=[
        ('xgb', xgb),
        ('lgbm', lgbm)
    ],
    final_estimator=meta_model,
    cv=TimeSeriesSplit(n_splits=3)
)

# Full pipeline
model = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', stacked_model)
])

def optimize_usage(property_features, model, pricing, carbon, flexibility=0.2):
    """
    Enhanced optimization with flexibility constraint

    Args:
        property_features: Property characteristics
        model: Trained consumption model
        pricing: List of prices for next 7 days
        carbon: List of carbon intensities for next 7 days
        flexibility: Max % change allowed (0.2 = 20%)

    Returns:
        Optimal schedule with constrained flexibility
    """
    # Create feature matrix for next 7 days
    days = 7
    X = pd.DataFrame(np.tile(property_features, (days, 1)),
                     columns=features)

    # Add temporal features
    future_dates = pd.date_range(start=pd.Timestamp.today(), periods=days)
    X['day_of_week'] = future_dates.dayofweek
    X['month'] = future_dates.month
    X['day_of_year'] = future_dates.dayofyear

    # Predict base consumption
    base_consumption = model.predict(X)

    # Optimization function
    def objective(adjustments):
        adjusted_consumption = base_consumption * adjustments
        costs = adjusted_consumption * pricing / 100
        carbon_emissions = adjusted_consumption * carbon / 1000

        # Weighted objective
        cost_term = 0.7 * costs.sum()
        carbon_term = 0.3 * carbon_emissions.sum()
        return cost_term + carbon_term

    # Constraints
    constraints = (
        {'type': 'ineq', 'fun': lambda x: 1 + flexibility - x},
        {'type': 'ineq', 'fun': lambda x: x - (1 - flexibility)},
        {'type': 'eq', 'fun': lambda x: np.sum(x) - len(x)}
    )

    # Bounds
    bounds = [(1 - flexibility, 1 + flexibility) for _ in range(days)]

    # Optimize
    result = minimize(objective, np.ones(days), method='SLSQP',
                      bounds=bounds, constraints=constraints)

    # Prepare results
    optimal_adjustments = result.x
    schedule = []
    for i, date in enumerate(future_dates):
        schedule.append({
            'date': date.strftime('%Y-%m-%d'),
            'recommended_usage': base_consumption[i] * optimal_adjustments[i],
            'base_usage': base_consumption[i],
            'price_per_kwh': pricing[i],
            'carbon_intensity': carbon[i],
            'adjustment': optimal_adjustments[i]
        })

    return schedule

# Commented out IPython magic to ensure Python compatibility.
# Install necessary libraries using pip first
# %pip install pandas numpy scikit-learn xgboost lightgbm shap matplotlib seaborn --quiet

import pandas as pd
import numpy as np
import gc  # Garbage collector interface
from google.colab import drive # Import drive for mounting Google Drive
import os # Import os for path manipulation

from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer # Corrected import for SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import TimeSeriesSplit, RandomizedSearchCV # TimeSeriesSplit for CV
from scipy.stats import uniform, randint
from sklearn.model_selection import train_test_split # Import train_test_split

import xgboost as xgb
import lightgbm as lgb
from sklearn.ensemble import StackingRegressor
from sklearn.linear_model import ElasticNetCV # More efficient for meta-learner tuning
from sklearn.metrics import mean_absolute_error, r2_score
import joblib
import matplotlib.pyplot as plt # For SHAP and residuals plots
import seaborn as sns # For residuals plots
import shap # For SHAP analysis
from datetime import datetime # For saving model with timestamp

# Mount Google Drive to access files
try:
    drive.mount('/content/drive')
    print("Google Drive mounted successfully.")
except Exception as e:
    print(f"Could not mount Google Drive. Error: {e}")
    raise

# --- 1. Load Data and Feature Engineering ---
print("Loading data and performing feature engineering...")

# Load dataset
df = pd.read_csv("/content/drive/MyDrive/optimisation_dataset.csv")
df['date'] = pd.to_datetime(df['date'])

# Feature engineering
df['day_of_year_sin'] = np.sin(2 * np.pi * df['date'].dt.dayofyear/365)
df['day_of_year_cos'] = np.cos(2 * np.pi * df['date'].dt.dayofyear/365)
df['hour_of_day'] = df['date'].dt.hour # If hourly data exists
df['day_of_week'] = df['date'].dt.dayofweek # Added for features list
df['month'] = df['date'].dt.month # Added for features list
df['season'] = (df['month'] % 12 + 3) // 3 # Added for features list

# Weather interactions
df['temp_humidity'] = df['max_temp_c'] * df['humidity_%']
df['temp_wind'] = df['max_temp_c'] * df['wind_speed_km/h']
df['weather_severity'] = (df['max_temp_c'] * 0.3 +
                          df['rain_mm'] * 0.2 +
                          df['wind_speed_km/h'] * 0.5)

# Property interactions
df['size_rating'] = df['TOTAL_FLOOR_AREA'] * df['CURRENT_ENERGY_RATING']
df['age_size'] = df['CONSTRUCTION_AGE_BAND'].astype('category').cat.codes * df['TOTAL_FLOOR_AREA']


# Sort by date and lclid before creating lags/rolling stats to ensure correct order within groups
df = df.sort_values(by=['lclid', 'date'])

# Lag features
for lag in [1, 2, 3, 7]: # Ensure these lags are consistent with your 'features' list
    df[f'lag_{lag}'] = df.groupby('lclid')['kwh_total'].shift(lag)

# Rolling statistics
df['rolling_7day_mean'] = df.groupby('lclid')['kwh_total'].transform(
    lambda x: x.rolling(7, min_periods=1).mean())
df['rolling_7day_std'] = df.groupby('lclid')['kwh_total'].transform(
    lambda x: x.rolling(7, min_periods=1).std())

# Handle missing values from lag/rolling features
df.fillna(method='ffill', inplace=True)
df.fillna(0, inplace=True) # Fill any NaNs at the very start of series that ffill couldn't handle
gc.collect() # Clean up memory after feature engineering


# --- 2. Prepare Features and Targets & Time-based Split ---
print("Preparing features and targets and performing time-based split...")

# Define features - ensure all engineered features are included
features = [
    # Original numerical features
    'min_temp_c', 'max_temp_c', 'rain_mm', 'humidity_%', 'cloud_cover_%',
    'wind_speed_km/h', 'wind_direction_numerical', 'TOTAL_FLOOR_AREA',
    'CURRENT_ENERGY_RATING',

    # Original categorical features
    'BUILT_FORM', 'PROPERTY_TYPE', 'CONSTRUCTION_AGE_BAND',

    # Engineered temporal features
    'day_of_year_sin', 'day_of_year_cos', 'hour_of_day',
    'day_of_week', 'month', 'season', # These were added in feature engineering

    # Engineered interaction features
    'temp_humidity', 'temp_wind', 'weather_severity', 'size_rating', 'age_size',

    # Engineered lag and rolling features
    'lag_1', 'lag_2', 'lag_3', 'lag_7',
    'rolling_7day_mean', 'rolling_7day_std'
]

target = 'kwh_total' # The target for this pipeline is kwh_total as per your tuning code

# Time-based split (2011-2013 for training, 2014 for testing)
train_df = df[df['date'].dt.year < 2014].copy() # Renamed to train_df to avoid conflict with 'train'
test_df = df[df['date'].dt.year == 2014].copy() # Renamed to test_df
# Keep original df for later prediction on full dataset if needed for dashboard
# del df # Free up memory from the full DataFrame - DO NOT DELETE YET IF YOU WANT TO ADD PREDICTED_KWH TO ORIGINAL DF
gc.collect()

X_train = train_df[features]
y_train = train_df[target]
X_test = test_df[features]
y_test = test_df[target]

# del train_df, test_df # Defer deletion until after predicted_kwh is added to test_df
gc.collect()

print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")


# --- 3. Preprocessing Pipeline Definition ---
print("Defining preprocessing pipeline...")

numeric_features = [f for f in features if f not in ['BUILT_FORM', 'PROPERTY_TYPE', 'CONSTRUCTION_AGE_BAND']]
categorical_features = ['BUILT_FORM', 'PROPERTY_TYPE', 'CONSTRUCTION_AGE_BAND']

preprocessor = ColumnTransformer(
    transformers=[
        # Numeric features: Impute missing values with the mean, then scale
        ('num', Pipeline(steps=[
            ('imputer', SimpleImputer(strategy='mean')),
            ('scaler', StandardScaler())
        ]), numeric_features),
        # Categorical features: Impute missing values with a constant 'missing', then one-hot encode
        ('cat', Pipeline(steps=[
            ('imputer', SimpleImputer(strategy='constant', fill_value='missing')),
            ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False)) # Set sparse_output=False
        ]), categorical_features)
    ])


# --- 4. Separate Tuning for Base Models (XGBoost and LightGBM) ---
print("\nStarting separate tuning for base models...")

# Reduce data size for tuning to speed up RandomizedSearchCV
tune_sample_size = min(500000, len(X_train))
sample_indices = np.random.choice(X_train.index, tune_sample_size, replace=False)
X_tune = X_train.loc[sample_indices].copy()
y_tune = y_train.loc[sample_indices].copy()

print(f"Using {len(X_tune)} samples for hyperparameter tuning.")
gc.collect() # Clean up memory after creating tune sample

def tune_model(model, param_dist, X, y, model_name):
    """Efficient model tuning with early stopping and RandomizedSearchCV."""
    # Split for validation within the tuning sample
    X_train_tune, X_val_tune, y_train_tune, y_val_tune = train_test_split(X, y, test_size=0.2, random_state=42)

    # --- CRITICAL FIX: Preprocess X_train_tune and X_val_tune explicitly here ---
    # This ensures the regressors always receive numerical input,
    # resolving the ValueError from XGBoost regarding 'object' dtypes.
    X_train_tune_processed = preprocessor.fit_transform(X_train_tune)
    X_val_tune_processed = preprocessor.transform(X_val_tune)
    gc.collect() # Clean up memory

    # Create a pipeline for the base model *without* the preprocessor, as data is already processed
    model_pipeline = Pipeline(steps=[
        ('regressor', model) # Only the regressor here
    ])

    # Create RandomizedSearchCV with reduced iterations and cross-validation
    search = RandomizedSearchCV(
        model_pipeline,
        param_dist,
        n_iter=15,
        cv=3,
        scoring='r2',
        verbose=2,
        n_jobs=-1,
        random_state=42
    )

    # Fit the pipeline with already processed data.
    # Passing eval_set directly to the regressor's fit method within RandomizedSearchCV
    # requires careful handling. For simplicity and to avoid the TypeError,
    # we're removing early_stopping_rounds and verbose from this tuning step.
    # Early stopping will be applied in the final training step (Step 5).
    search.fit(X_train_tune_processed, y_train_tune,
               regressor__eval_set=[(X_val_tune_processed, y_val_tune)]
              )

    print(f"{model_name} Best Params:", search.best_params_)
    print(f"{model_name} Best R² (CV score):", search.best_score_)

    # Save the best estimator (which is now just the regressor itself, not the pipeline with preprocessor)
    joblib.dump(search.best_estimator_.named_steps['regressor'], f'/content/drive/MyDrive/best_tuned_{model_name}_regressor.pkl')
    return search.best_estimator_.named_steps['regressor']


# Tune XGBoost separately
xgb_params = {
    'regressor__n_estimators': randint(300, 600),
    'regressor__max_depth': randint(6, 10),
    'regressor__learning_rate': uniform(0.03, 0.07),
    'regressor__subsample': uniform(0.7, 0.2),
    'regressor__colsample_bytree': uniform(0.7, 0.2),
    'regressor__gamma': uniform(0, 0.3)
}

best_xgb_regressor = tune_model(
    xgb.XGBRegressor(tree_method='hist', device='cuda', random_state=42, enable_categorical=True), # Changed gpu_id to device='cuda'
    xgb_params,
    X_tune,
    y_tune,
    'xgb'
)
gc.collect()

# Tune LightGBM separately
lgbm_params = {
    'regressor__n_estimators': randint(300, 600),
    'regressor__max_depth': randint(6, 10),
    'regressor__learning_rate': uniform(0.03, 0.07),
    'regressor__subsample': uniform(0.7, 0.2),
    'regressor__colsample_bytree': uniform(0.7, 0.2),
    'regressor__reg_alpha': uniform(0, 0.5),
    'regressor__reg_lambda': uniform(0, 0.5)
}

best_lgbm_regressor = tune_model(
    lgb.LGBMRegressor(device='gpu', random_state=42),
    lgbm_params,
    X_tune,
    y_tune,
    'lgbm'
)
gc.collect()
del X_tune, y_tune
gc.collect()


# --- 5. Train Base Models on Full Training Data and Get Predictions ---
print("\nTraining best base models on full training data and generating predictions...")

# Preprocess X_train and X_test once for efficiency
# preprocessor is fitted on X_train here, then used to transform both.
X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)
gc.collect()

# Train best_xgb_regressor on full X_train_processed
# Removed eval_set, early_stopping_rounds, verbose from here as well,
# as the tuning already found the optimal n_estimators.
best_xgb_regressor.fit(X_train_processed, y_train)
xgb_preds_train = best_xgb_regressor.predict(X_train_processed)
xgb_preds_test = best_xgb_regressor.predict(X_test_processed)
gc.collect()

# Train best_lgbm_regressor on full X_train_processed
# Removed eval_set, early_stopping_rounds, verbose from here as well.
best_lgbm_regressor.fit(X_train_processed, y_train)
lgbm_preds_train = best_lgbm_regressor.predict(X_train_processed)
lgbm_preds_test = best_lgbm_regressor.predict(X_test_processed)
gc.collect()

# Stack predictions for meta-learner
stacked_features_train = np.column_stack([xgb_preds_train, lgbm_preds_train])
stacked_features_test = np.column_stack([xgb_preds_test, lgbm_preds_test])
gc.collect()


# --- 6. Tune and Train Meta-Learner Separately ---
print("\nTuning and training meta-learner...")

meta_model = ElasticNetCV(
    l1_ratio=[.1, .5, .7, .9, .95, .99, 1],
    cv=5,
    n_jobs=-1,
    random_state=42,
    max_iter=10000 # Increased max_iter to help with convergence warning
)
meta_model.fit(stacked_features_train, y_train)
print("Meta-model Best alpha:", meta_model.alpha_)
print("Meta-model Best l1_ratio:", meta_model.l1_ratio_)
gc.collect()


# --- 7. Final Ensemble Model (Optional: Re-stacking or direct prediction) ---
print("\nCombining predictions for final ensemble...")
final_ensemble_preds = meta_model.predict(stacked_features_test)


# --- 8. Evaluate Final Ensemble ---
print("\nEvaluating final ensemble model...")
r2 = r2_score(y_test, final_ensemble_preds)
mae = mean_absolute_error(y_test, final_ensemble_preds)

print(f"Final Ensemble Model Performance:")
print(f"R²: {r2:.4f}")
print(f"MAE: {mae:.4f} kWh")


# --- 9. SHAP Analysis (using the best XGBoost regressor as an example for interpretability) ---
print("\nPerforming SHAP analysis (interpreting best XGBoost regressor)...")

# SHAP needs the features in the format the model expects (i.e., processed)
# X_train_processed is already available from step 5.
shap_sample_size = min(5000, X_train_processed.shape[0])
sample_indices_shap = np.random.choice(X_train_processed.shape[0], shap_sample_size, replace=False)
X_train_processed_sample = X_train_processed[sample_indices_shap]

# preprocessor was already fitted on X_train in step 5, no need to fit again.
# feature_names are needed for SHAP plots.
feature_names = preprocessor.get_feature_names_out(features)

explainer = shap.Explainer(best_xgb_regressor)
shap_values = explainer(X_train_processed_sample)

print("Generating SHAP summary plot...")
shap.summary_plot(shap_values, X_train_processed_sample, feature_names=feature_names, plot_type="bar", show=False)
plt.title("Feature Importance (from Best XGBoost Regressor)")
plt.tight_layout()
plt.show()

print("Generating SHAP dependence plots...")
# Corrected feature names for dependence plots to match the processed output
# These should be in the format 'num_feature_name' or 'cat_category_value'
top_features_for_plot_processed = [
    'num_TOTAL_FLOOR_AREA',
    'num_rolling_7day_mean',
    'num_max_temp_c',
    'num_lag_1'
]
for feature_name_processed in top_features_for_plot_processed:
    try:
        # Find the index of the feature in the processed array
        feature_idx = list(feature_names).index(feature_name_processed)
        shap.dependence_plot(feature_idx, shap_values.values, X_train_processed_sample, feature_names=feature_names, show=False)
        plt.title(f"{feature_name_processed.replace('num_', '')} Dependence (from Best XGBoost Regressor)") # Clean up title
        plt.tight_layout()
        plt.show()
    except ValueError:
        print(f"Warning: Processed feature '{feature_name_processed}' not found. Skipping dependence plot.")
gc.collect()


# --- 10. Residuals Analysis ---
print("\nPerforming residuals analysis...")

# Add predicted_kwh to test_df for residuals plotting
test_df['predicted_kwh'] = final_ensemble_preds # Add this line

residuals = y_test - final_ensemble_preds

plt.figure(figsize=(12, 6))
sns.histplot(residuals, kde=True)
plt.title("Residuals Distribution")
plt.xlabel("Prediction Error (kWh)")
plt.show()
gc.collect()

plt.figure(figsize=(12, 6))
sns.scatterplot(x=final_ensemble_preds, y=residuals, alpha=0.3)
plt.axhline(0, color='red', linestyle='--')
plt.title("Residuals vs Predicted Values")
plt.xlabel("Predicted Consumption (kWh)")
plt.ylabel("Residuals")
plt.show()
gc.collect()

# For residuals by feature, use the original X_test features for plotting clarity
for feature in ['TOTAL_FLOOR_AREA', 'max_temp_c', 'day_of_year_sin']:
    if feature in X_test.columns:
        plt.figure(figsize=(12, 6))
        sns.scatterplot(x=X_test[feature], y=residuals, alpha=0.3)
        plt.axhline(0, color='red', linestyle='--')
        plt.title(f"Residuals by {feature}")
        plt.xlabel(feature)
        plt.ylabel("Residuals")
        plt.show() # Changed to plt.show()
    else:
        print(f"Warning: Feature '{feature}' not found in X_test for residuals plot. Skipping.")


# --- 11. Save Final Model and Features ---
print("\nSaving final model and features list...")

joblib.dump(meta_model, f'/content/drive/MyDrive/meta_model_{datetime.now().strftime("%Y%m%d_%H%M")}.pkl')
joblib.dump(best_xgb_regressor, f'/content/drive/MyDrive/best_xgb_regressor_{datetime.now().strftime("%Y%m%d_%H%M")}.pkl')
joblib.dump(best_lgbm_regressor, f'/content/drive/MyDrive/best_lgbm_regressor_{datetime.now().strftime("%Y%m%d_%H%M")}.pkl')
joblib.dump(preprocessor, f'/content/drive/MyDrive/preprocessor_{datetime.now().strftime("%Y%m%d_%H%M")}.pkl')

# Save feature list
features_path = f"/content/drive/MyDrive/model_features_{datetime.now().strftime('%Y%m%d_%H%M')}.pkl"
joblib.dump(features, features_path)

# --- Save the original df with predicted_kwh for dashboard use ---
# This ensures the dashboard has the 'predicted_kwh' column for its plots.
# Assuming 'df' still holds the original full dataset (before train/test split)
# If 'df' was deleted, you'd need to reconstruct it or only save test_df with predictions.
# For simplicity, let's assume 'df' is available and we add predictions to it.
# If not, you'd need to reload it: df = pd.read_csv("/content/drive/MyDrive/optimisation_dataset.csv")

# Preprocess the full original dataframe
df_processed_for_full_prediction = preprocessor.transform(df[features])

# Get predictions from base models on the full processed data
xgb_preds_full = best_xgb_regressor.predict(df_processed_for_full_prediction)
lgbm_preds_full = best_lgbm_regressor.predict(df_processed_for_full_prediction)

# Stack predictions for meta-model on full data
stacked_predictions_full = np.column_stack([xgb_preds_full, lgbm_preds_full])

# Get final prediction from meta-model on full data
df['predicted_kwh'] = meta_model.predict(stacked_predictions_full) # Add as new column

# Save the updated optimisation_dataset.csv with predicted_kwh
df.to_csv("/content/drive/MyDrive/optimisation_dataset.csv", index=False)
print("Updated 'optimisation_dataset.csv' with 'predicted_kwh' column.")


print(f"Meta-model saved to /content/drive/MyDrive/meta_model_....pkl")
print(f"Best XGBoost Regressor saved to /content/drive/MyDrive/best_xgb_regressor_....pkl")
print(f"Best LightGBM Regressor saved to /content/drive/MyDrive/best_lgbm_regressor_....pkl")
print(f"Preprocessor saved to /content/drive/MyDrive/preprocessor_....pkl")
print(f"Features list saved to {features_path}")

print("\nPipeline execution complete.")
