# -*- coding: utf-8 -*-
"""energy_api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KoqXfYcNgGd8uVED1UhYyu8C4znDKEMf
"""

# energy_api.py

# Install necessary libraries if running standalone (e.g., in a new environment)
# pip install fastapi uvicorn pandas numpy scikit-learn xgboost lightgbm joblib pydantic

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field # Import Field for aliases
import pandas as pd
import numpy as np
import joblib
import os
from datetime import datetime, date, timedelta # Import timedelta for date calculations

# Initialize FastAPI app
app = FastAPI(
    title="Energy Consumption Prediction API",
    description="API for predicting energy consumption based on various features.",
    version="1.0.0"
)

# --- Define paths to your saved models and preprocessor ---
# Assuming you've created an 'models' subdirectory inside your 'api' folder
# and renamed the files to generic names (e.g., 'best_xgb_regressor.pkl')
MODELS_DIR = os.path.join(os.path.dirname(__file__), "models") # Points to 'api/models/'

# Global variables to hold the loaded models and preprocessor
preprocessor = None
best_xgb_regressor = None
best_lgbm_regressor = None
meta_model = None
features_list = None # This will store the list of feature names your model expects

def load_artifacts():
    """Loads the preprocessor, base models, meta-model, and features list."""
    global preprocessor, best_xgb_regressor, best_lgbm_regressor, meta_model, features_list

    try:
        # Construct full paths to the generically named files
        xgb_model_path = os.path.join(MODELS_DIR, "best_xgb_regressor.pkl")
        lgbm_model_path = os.path.join(MODELS_DIR, "best_lgbm_regressor.pkl")
        meta_model_path = os.path.join(MODELS_DIR, "meta_model.pkl")
        preprocessor_path = os.path.join(MODELS_DIR, "preprocessor.pkl")
        features_list_path = os.path.join(MODELS_DIR, "model_features.pkl")

        # Check if all files exist before attempting to load
        if not (os.path.exists(xgb_model_path) and
                os.path.exists(lgbm_model_path) and
                os.path.exists(meta_model_path) and
                os.path.exists(preprocessor_path) and
                os.path.exists(features_list_path)):
            raise FileNotFoundError(
                f"One or more model/preprocessor/features files not found in {MODELS_DIR}. "
                "Please ensure they are downloaded and renamed as instructed."
            )

        best_xgb_regressor = joblib.load(xgb_model_path)
        best_lgbm_regressor = joblib.load(lgbm_model_path)
        meta_model = joblib.load(meta_model_path)
        preprocessor = joblib.load(preprocessor_path)
        features_list = joblib.load(features_list_path)

        print("All machine learning artifacts loaded successfully.")
    except Exception as e:
        print(f"Error loading ML artifacts: {e}")
        raise RuntimeError(f"Failed to load ML artifacts: {e}")

# Load artifacts when the application starts
load_artifacts()


# --- Mock External Data Sources (For Demonstration Purposes) ---
# In a real application, these would be calls to external APIs or databases
def _get_mock_carbon_intensity(hour_of_day: int) -> float:
    """Mock function to get carbon intensity (kgCO2/kWh) based on hour."""
    # Simulate lower intensity during off-peak and higher during peak
    if 0 <= hour_of_day < 6: # Night
        return 0.15
    elif 6 <= hour_of_day < 10: # Morning peak
        return 0.35
    elif 10 <= hour_of_day < 17: # Day off-peak
        return 0.20
    elif 17 <= hour_of_day < 22: # Evening peak
        return 0.45
    else: # Late night
        return 0.25

def _get_mock_price_per_kwh(hour_of_day: int) -> float:
    """Mock function to get price per kWh (pence/kWh) based on hour."""
    # Simulate lower price during off-peak and higher during peak
    if 0 <= hour_of_day < 6: # Night
        return 10.0 # 10p/kWh
    elif 6 <= hour_of_day < 10: # Morning peak
        return 25.0 # 25p/kWh
    elif 10 <= hour_of_day < 17: # Day off-peak
        return 15.0 # 15p/kWh
    elif 17 <= hour_of_day < 22: # Evening peak
        return 30.0 # 30p/kWh
    else: # Late night
        return 12.0 # 12p/kWh


# --- Define Input Data Model for Prediction Endpoint ---
class EnergyPredictRequest(BaseModel):
    min_temp_c: float
    max_temp_c: float
    rain_mm: float
    humidity_percent: float = Field(alias='humidity_%')
    cloud_cover_percent: float = Field(alias='cloud_cover_%')
    wind_speed_km_h: float = Field(alias='wind_speed_km/h')
    wind_direction_numerical: float
    total_floor_area: float = Field(alias='TOTAL_FLOOR_AREA')
    current_energy_rating: float = Field(alias='CURRENT_ENERGY_RATING')
    built_form: str = Field(alias='BUILT_FORM')
    property_type: str = Field(alias='PROPERTY_TYPE')
    construction_age_band: str = Field(alias='CONSTRUCTION_AGE_BAND')
    day_of_week: int
    month: int
    season: int
    day_of_year_sin: float
    day_of_year_cos: float
    hour_of_day: int
    temp_humidity: float
    temp_wind: float
    weather_severity: float
    size_rating: float
    age_size: float
    lag_1: float
    lag_2: float
    lag_3: float
    lag_7: float
    rolling_7day_mean: float
    rolling_7day_std: float

    class Config:
        populate_by_name = True


# --- Prediction Endpoint (Existing) ---
@app.post("/predict", summary="Predict energy consumption (kWh)")
async def predict_energy_consumption(request: EnergyPredictRequest):
    """
    Predicts energy consumption (kWh) based on the provided input features.
    """
    try:
        input_data_dict = request.model_dump(by_alias=True)
        input_df = pd.DataFrame([input_data_dict])[features_list] # Ensure order matches training

        processed_input = preprocessor.transform(input_df)

        xgb_pred = best_xgb_regressor.predict(processed_input)
        lgbm_pred = best_lgbm_regressor.predict(processed_input)
        stacked_predictions = np.column_stack([xgb_pred, lgbm_pred])

        final_prediction = meta_model.predict(stacked_predictions)[0]

        return {"predicted_kwh": float(final_prediction)}

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Prediction failed: {e}")


# --- Define Input Data Model for Optimization Endpoint ---
class ApplianceOptimizationRequest(BaseModel):
    # Features required for baseline energy prediction
    min_temp_c: float
    max_temp_c: float
    rain_mm: float
    humidity_percent: float = Field(alias='humidity_%')
    cloud_cover_percent: float = Field(alias='cloud_cover_%')
    wind_speed_km_h: float = Field(alias='wind_speed_km/h')
    wind_direction_numerical: float
    total_floor_area: float = Field(alias='TOTAL_FLOOR_AREA')
    current_energy_rating: float = Field(alias='CURRENT_ENERGY_RATING')
    built_form: str = Field(alias='BUILT_FORM')
    property_type: str = Field(alias='PROPERTY_TYPE')
    construction_age_band: str = Field(alias='CONSTRUCTION_AGE_BAND')
    # For now, these are direct inputs. In a real system, would be looked up by lclid
    lag_1: float
    lag_2: float
    lag_3: float
    lag_7: float
    rolling_7day_mean: float
    rolling_7day_std: float

    # Appliance specific inputs
    appliance_name: str
    appliance_kwh_per_cycle: float = Field(description="Energy consumed by the appliance per cycle in kWh.")
    optimization_date: date = Field(description="The date for which to find the optimal time to run the appliance.")
    flexible_start_hour: int = Field(ge=0, le=23, description="Start hour (0-23) of the flexible time window.")
    flexible_end_hour: int = Field(ge=0, le=23, description="End hour (0-23) of the flexible time window.")
    # Add weights for optimization objective (e.g., prioritize cost vs. carbon)
    cost_weight: float = Field(default=0.5, ge=0, le=1, description="Weight given to cost in optimization (0-1).")
    carbon_weight: float = Field(default=0.5, ge=0, le=1, description="Weight given to carbon in optimization (0-1).")

    class Config:
        populate_by_name = True


# --- Optimization Endpoint (New) ---
@app.post("/optimize_appliance", summary="Find optimal time to run an appliance")
async def optimize_appliance(request: ApplianceOptimizationRequest):
    """
    Finds the optimal hour within a flexible window to run an appliance
    to minimize a weighted combination of energy cost and carbon footprint.
    """
    if request.flexible_start_hour > request.flexible_end_hour:
        raise HTTPException(status_code=400, detail="Flexible start hour cannot be after end hour.")

    best_hour = -1
    min_objective_value = float('inf')
    predictions_and_costs = []

    # Iterate through each hour in the flexible window
    for current_hour in range(request.flexible_start_hour, request.flexible_end_hour + 1):
        # 1. Prepare input for baseline energy prediction for this hour
        prediction_date = request.optimization_date
        day_of_week = prediction_date.weekday()
        month = prediction_date.month
        season = (month % 12 + 3) // 3
        day_of_year_sin = np.sin(2 * np.pi * prediction_date.timetuple().tm_yday/365)
        day_of_year_cos = np.cos(2 * np.pi * prediction_date.timetuple().tm_yday/365)

        # Derived features based on current hour's weather data
        temp_humidity = request.max_temp_c * request.humidity_percent
        temp_wind = request.max_temp_c * request.wind_speed_km_h
        weather_severity = (request.max_temp_c * 0.3 + request.rain_mm * 0.2 + request.wind_speed_km_h * 0.5)
        size_rating = request.total_floor_area * request.current_energy_rating
        # age_size is tricky without knowing the OneHotEncoder's mapping for CONSTR_AGE_BAND
        # For simplicity, using a fixed value for demo, assuming its impact is consistent
        # In a real system, you'd need the actual numeric code from the preprocessor for this categorical.
        age_size_val = 5000.0 # Placeholder, adjust if you have a mapping

        input_data_for_baseline = {
            "min_temp_c": request.min_temp_c,
            "max_temp_c": request.max_temp_c,
            "rain_mm": request.rain_mm,
            "humidity_%": request.humidity_percent,
            "cloud_cover_%": request.cloud_cover_percent,
            "wind_speed_km/h": request.wind_speed_km_h,
            "wind_direction_numerical": request.wind_direction_numerical,
            "TOTAL_FLOOR_AREA": request.total_floor_area,
            "CURRENT_ENERGY_RATING": request.current_energy_rating,
            "BUILT_FORM": request.built_form,
            "PROPERTY_TYPE": request.property_type,
            "CONSTRUCTION_AGE_BAND": request.construction_age_band,
            "day_of_week": day_of_week,
            "month": month,
            "season": season,
            "day_of_year_sin": float(day_of_year_sin),
            "day_of_year_cos": float(day_of_year_cos),
            "hour_of_day": current_hour, # This changes per iteration
            "temp_humidity": temp_humidity,
            "temp_wind": temp_wind,
            "weather_severity": weather_severity,
            "size_rating": size_rating,
            "age_size": age_size_val, # Using placeholder
            "lag_1": request.lag_1,
            "lag_2": request.lag_2,
            "lag_3": request.lag_3,
            "lag_7": request.lag_7,
            "rolling_7day_mean": request.rolling_7day_mean,
            "rolling_7day_std": request.rolling_7day_std
        }

        # Ensure all features in `features_list` are present in `input_data_for_baseline`
        # and are in the correct order. This is critical for `preprocessor.transform`.
        # Create a DataFrame ensuring column order.
        try:
            input_df = pd.DataFrame([input_data_for_baseline])[features_list]
        except KeyError as e:
            raise HTTPException(status_code=500, detail=f"Missing feature in input data for baseline prediction: {e}. "
                                                        "This is likely due to a mismatch between API request fields "
                                                        "and the model's expected features_list.")

        # Preprocess the input data
        processed_input = preprocessor.transform(input_df)

        # Get baseline energy prediction
        xgb_pred = best_xgb_regressor.predict(processed_input)
        lgbm_pred = best_lgbm_regressor.predict(processed_input)
        stacked_predictions = np.column_stack([xgb_pred, lgbm_pred])
        baseline_kwh = meta_model.predict(stacked_predictions)[0]

        # 2. Add appliance consumption to baseline
        total_kwh_with_appliance = baseline_kwh + request.appliance_kwh_per_cycle

        # 3. Get mock carbon intensity and price for this hour
        carbon_intensity = _get_mock_carbon_intensity(current_hour)
        price_per_kwh = _get_mock_price_per_kwh(current_hour)

        # 4. Calculate total cost and carbon for this hour
        total_cost = total_kwh_with_appliance * price_per_kwh / 100 # Convert pence to pounds
        total_carbon = total_kwh_with_appliance * carbon_intensity

        # 5. Calculate objective value (weighted sum of cost and carbon)
        # Normalize cost and carbon if their scales are vastly different
        # For this demo, assuming similar scale or that the weights handle it.
        # In a real scenario, you might want to normalize cost and carbon to a 0-1 scale
        # before applying weights, to ensure fair weighting.
        objective_value = (request.cost_weight * total_cost) + (request.carbon_weight * total_carbon)

        predictions_and_costs.append({
            "hour": current_hour,
            "baseline_kwh": float(baseline_kwh),
            "appliance_kwh": float(request.appliance_kwh_per_cycle),
            "total_kwh": float(total_kwh_with_appliance),
            "carbon_intensity_kgCO2_per_kWh": float(carbon_intensity),
            "price_pence_per_kWh": float(price_per_kwh),
            "total_cost_pounds": float(total_cost),
            "total_carbon_kgCO2": float(total_carbon),
            "objective_value": float(objective_value)
        })

        # 6. Check for optimal hour
        if objective_value < min_objective_value:
            min_objective_value = objective_value
            best_hour = current_hour

    # Find the details for the best hour
    best_hour_details = next((item for item in predictions_and_costs if item["hour"] == best_hour), None)

    return {
        "optimization_date": request.optimization_date.isoformat(),
        "appliance_name": request.appliance_name,
        "flexible_window": f"{request.flexible_start_hour}:00 - {request.flexible_end_hour}:00",
        "optimal_hour_to_run": best_hour,
        "optimal_hour_details": best_hour_details,
        "all_hours_details": predictions_and_costs,
        "message": f"To minimize cost and carbon for your {request.appliance_name}, the optimal time to run it is at {best_hour}:00 on {request.optimization_date.isoformat()}."
    }

# --- Health Check Endpoint ---
@app.get("/health")
async def health_check():
    """
    Health check endpoint to verify API is running and models are loaded.
    """
    if all([preprocessor, best_xgb_regressor, best_lgbm_regressor, meta_model, features_list]):
        return {"status": "ok", "message": "API is running and models are loaded."}
    else:
        raise HTTPException(status_code=503, detail="API is running but models failed to load.")


# To run this API locally (for testing):
# 1. Save this code as energy_api.py in your 'energy-optimization/api/' directory.
# 2. Create a 'models/' subdirectory inside 'api/'.
# 3. Download and rename your .pkl model files into 'api/models/'.
# 4. Open your terminal in the 'energy-optimization/api/' directory.
# 5. Run: pip install -r requirements.txt
# 6. Run: uvicorn energy_api:app --reload --port 8000
# You can then access the API documentation at http://127.0.0.1:8000/docs
